attendy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('summernote/', include('django_summernote.urls')),
    path('__reload__/', include("django_browser_reload.urls")),
    path('accounts/', include('allauth.urls')),
]

# Handlers for 404 and 500 errors
handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from .views import HomeView, DashboardView, CourseView, StudentView, LecturerView, TeachingRecordView, \
    TeachingRecordDetailView, CourseDetailView, StudentDetailView, LecturerDetailView, LecturerAddView, \
    StudentAddView, CourseAddView, CourseUpdateView, StudentUpdateView, LecturerUpdateView, \
    TeachingRecordUpdateView, LevelView, DashboardDetailView, AttendanceDetailView, AttendanceAddView, \
    CourseAttendanceAddView, AttendanceUpdateView, decode_qr, add_student_to_course_attendance, FeedbackView, \
    CourseRegistrationView, CourseStudentsPDFView, AttendancePDFView, TeachingRecordPDFView, StudentPDFView, \
    DownloadTemplateFileView, LecturerPDFView, CourseListPDFView, DashboardUpdateView

# Create your urls here
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    # Class levels URLs
    path('levels/', LevelView.as_view(), name='levels'),

    # Course URLs
    path('app/<int:level_pk>/courses/', CourseView.as_view(), name='courses'),
    path('app/<int:level_pk>/courses/pdf/', CourseListPDFView.as_view(), name='courses_pdf'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>', CourseDetailView.as_view(), name='course_detail'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>/pdf/', CourseStudentsPDFView.as_view(), name='course_pdf'),
    path('app/<int:level_pk>/courses/add/', CourseAddView.as_view(), name='course_add'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>/edit', CourseUpdateView.as_view(), name='course_update'),

    # Student URLs
    path('app/<int:level_pk>/students/', StudentView.as_view(), name='students'),
    path('app/<int:level_pk>/<str:model_name>/download-template/', DownloadTemplateFileView.as_view(), name='download_template'),
    path('app/<int:level_pk>/students/pdf/', StudentPDFView.as_view(), name='students_pdf'),
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/', StudentDetailView.as_view(), name='student_detail'),
    path('app/<int:level_pk>/students/add', StudentAddView.as_view(), name='student_add'),
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/edit/', StudentUpdateView.as_view(), name='student_update'),

    # Course Registration URLs
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/register-courses/', CourseRegistrationView.as_view(),
         name='course_registration'),

    # Lecturer URLs
    path('app/<int:level_pk>/lecturers/', LecturerView.as_view(), name='lecturers'),
    path('app/<int:level_pk>/lecturers/pdf/', LecturerPDFView.as_view(), name='lecturers_pdf'),
    path('app/<int:level_pk>/lecturers/<int:pk>/<slug:slug>/', LecturerDetailView.as_view(),
         name='lecturer_detail'),
    path('app/<int:level_pk>/lecturers/add/', LecturerAddView.as_view(), name='lecturer_add'),
    path('app/<int:level_pk>/lecturers/<int:pk>/<slug:slug>/edit', LecturerUpdateView.as_view(),
         name='lecturer_update'),

    # Teaching Record URLs
    path('app/<int:level_pk>/records/', TeachingRecordView.as_view(), name='records'),
    path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/', TeachingRecordDetailView.as_view(),
         name='record_detail'),
path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/pdf/', TeachingRecordPDFView.as_view(),
         name='record_pdf'),
    path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/edit', TeachingRecordUpdateView.as_view(),
         name='record_update'),

    # Dashboard URLs
    path('app/<int:level_pk>/<slug:level_slug>/', DashboardView.as_view(), name='dashboard'),
    path('app/<int:level_pk>/<slug:level_slug>/overview/', DashboardDetailView.as_view(), name='dashboard_detail'),
    path('app/<int:level_pk>/<slug:level_slug>/overview/update/', DashboardUpdateView.as_view(), name='dashboard_update'),

    # Attendance URLs
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/', AttendanceDetailView.as_view(),
         name='attendance_detail'),
path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/pdf/', AttendancePDFView.as_view(),
         name='attendance_pdf'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/edit/', AttendanceUpdateView.as_view(),
         name='attendance_update'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/add/', AttendanceAddView.as_view(), name='attendance_add'),

    # Enrollment URLs
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/admit/', CourseAttendanceAddView.as_view(),
         name='enroll_add'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/scan/', decode_qr, name='decode_qr'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/scan/admit/', add_student_to_course_attendance,
         name='add_student_to_course_attendance'),

    # Feedback URLs
    path('app/feedback/', FeedbackView.as_view(), name='feedback'), 
]

core/views.py
import csv
import json
import os
import random
from collections import defaultdict
from datetime import timedelta, datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Q, Count, Sum
from django.http import JsonResponse, FileResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.html import format_html
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, View
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image

from .forms import CourseForm, LecturerForm, StudentForm, TeachingRecordForm, AttendanceForm, CourseAttendanceForm, \
    FeedbackForm, ClassLevelForm
from .mixins import CommonContextMixin, ClassLevelAccessMixin
from .models import Course, Student, Lecturer, TeachingRecord, CourseDelegate, CourseAttendance, \
    ClassLevel, Attendance, ClassLevelUser, Feedback, CourseRegistration
from .utils import group_model_items_by_week, get_faqs, get_quotes, decode_data, date_formatter, time_formatter, \
    short_date_formatter, parse_html_to_flowables


# Create your views here.
class HomeView(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['levels_count'] = ClassLevel.objects.all().count()
        context['course_attendance_count'] = Attendance.objects.all().count()
        context['courses_count'] = Course.objects.all().count()
        context['lecturers_count'] = Lecturer.objects.all().count()
        context['students_count'] = Student.objects.all().count()
        context['faqs'] = get_faqs
        context['current_year'] = datetime.now().year
        return context


class LevelView(LoginRequiredMixin, ListView):
    model = ClassLevel
    template_name = 'core/dashboard/levels.html'
    context_object_name = 'levels'
    paginate_by = 25

    def get_queryset(self):
        if self.request.user.is_superuser:
            return ClassLevel.objects.all().order_by('year', 'semester')
        return ClassLevel.objects.filter(class_level_users__user=self.request.user).order_by('year', 'semester')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_year'] = datetime.now().year
        return context


# Dashboard views
def group_items_by_week(attendances):
    grouped_attendances = defaultdict(list)
    for attendance in attendances.order_by('created_at'):
        # Calculate the start of the week (Monday) for each item
        week_start = attendance.created_at - timedelta(days=attendance.created_at.weekday())
        week_end = week_start + timedelta(days=6)

        # Format the week range as "Mon 19 Aug - Sun 25 Aug"
        week_range = f"{week_start.strftime('%a %d %b')} - {week_end.strftime('%a %d %b %Y')}"

        # Group items by this week range
        grouped_attendances[week_range].append(attendance)

    return dict(grouped_attendances)


# core/views.py
class DashboardView(LoginRequiredMixin, CommonContextMixin, ClassLevelAccessMixin, DetailView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard.html'
    context_object_name = 'level'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        grouped_attendances = group_items_by_week(
            Attendance.objects.filter(class_level=self.kwargs['level_pk'])
        )
        for week, attendances in grouped_attendances.items():
            for attendance in attendances:
                attendance.course_delegate = CourseDelegate.objects.filter(course=attendance.course,
                                                                           role='delegate').first()
                attendance.course_assistant = CourseDelegate.objects.filter(course=attendance.course,
                                                                            role='assistant').first()
                attendance.enrollment_count = CourseAttendance.objects.filter(attendance=attendance).count()
        context['grouped_attendances'] = dict(grouped_attendances)

        # Calculate number of attendances per course, including courses with zero attendance
        courses = Course.objects.filter(class_level=self.kwargs['level_pk'])
        course_attendance_counts = courses.annotate(count=Count('course_attendance')).values('title', 'count').order_by(
            'title')
        context['course_attendance_counts'] = json.dumps(list(course_attendance_counts))

        return context


class DashboardDetailView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard_details.html'
    context_object_name = 'level'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = ClassLevelUser.objects.filter(class_level=self.kwargs['level_pk'])
        return context


class DashboardUpdateView(LoginRequiredMixin, CommonContextMixin, UpdateView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard_update.html'
    context_object_name = 'form'
    form_class = ClassLevelForm

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_success_url(self):
        return reverse_lazy('core:dashboard_detail', kwargs={'level_pk': self.kwargs['level_pk'], 'level_slug': self.kwargs['level_slug']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['class_level'] = self.get_object()
        return context

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Class info updated successfully.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'An error occurred while updating class info. Please try again.')
        return super().form_invalid(form)

class AttendanceDetailView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = Attendance
    template_name = 'core/attendance/attendance_details.html'
    context_object_name = 'attendance'

    def get_object(self, queryset=None):
        return get_object_or_404(
            self.model,
            class_level=self.kwargs['level_pk'],
            class_level__slug=self.kwargs['level_slug'],
            id=self.kwargs['pk']
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course_delegates'] = CourseDelegate.objects.filter(
            course=self.object.course,
            student__is_delegate=True
        )
        context['enrollments'] = CourseAttendance.objects.filter(attendance=self.object,
                                                                 attendance__class_level=self.kwargs[
                                                                     'level_pk']).order_by('created_at')
        return context

    def post(self, request, *args, **kwargs):
        if 'delete_enrollment' in request.POST:
            enrollment_id = request.POST.get('enrollment_id')
            enrollment = CourseAttendance.objects.get(id=enrollment_id)
            enrollment.delete()
            message = format_html(
                '<strong>{}</strong> was removed successfully.',
                enrollment.student.name
            )
            messages.success(request, message)
        return self.get(request, *args, **kwargs)


class AttendancePDFView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = Attendance
    template_name = 'core/attendance/attendance_details.html'
    context_object_name = 'attendance'

    def get(self, request, *args, **kwargs):
        attendance = self.get_object()
        course_delegate = CourseDelegate.objects.filter(course=attendance.course, student__is_delegate=True,
                                                        role='delegate')
        enrollments = CourseAttendance.objects.filter(attendance=self.get_object(),
                                                      attendance__class_level=self.kwargs[
                                                          'level_pk']).order_by('created_at')

        # Generate PDF file path
        filename = f"{attendance.course.title}_attendance_sheet_{attendance.course_date}.pdf"
        pdf_folder_path = os.path.join(settings.MEDIA_ROOT, 'attendance_sheets')
        os.makedirs(pdf_folder_path, exist_ok=True)
        pdf_file_path = os.path.join(pdf_folder_path, filename)

        doc = SimpleDocTemplate(pdf_file_path, title=filename, pagesize=A4, rightMargin=24, leftMargin=24, topMargin=20,
                                bottomMargin=18)
        elements = []

        # Add the image at the top
        image_path = str(settings.BASE_DIR / 'static/core/images/ictu_logo.png')
        logo = Image(image_path)
        logo.drawHeight = 1.25 * inch
        logo.drawWidth = 1.25 * inch
        elements.append(logo)

        styles = getSampleStyleSheet()
        styles['Normal'].leading = 20

templates/core/levels/levels.html
{% extends 'core/base.html' %}
{% load static %}
{% load tailwind_tags custom_date_formatter number_formatting %}

{# Title of the page #}
{% block title %}Sigin into a class{% endblock %}

{# Body styles #}
{% block body_styles %} 
{% endblock body_styles %}

{# Body of the page #}
{% block body %}
<main>
    <div
        class="absolute inset-0 h-dvh w-full bg-whiteColor bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px]">
        <div class="overflow-hidden flex flex-col items-center justify-center gap-4 h-screen text-center px-4 lg:p-0">
            <img src="{% static 'core/images/attendy-text.svg' %}" alt="">
            <div class="flex gap-2 outline outline-1 outline-gray-500 text-gray-500 ps-[3px] pe-4 py-0.5 rounded-full backdrop-blur-md">
                <small class="flex items-center gap-1">
                    <span class="flex items-center gap-1 font-bold bg-primaryColor text-whiteColor px-3 py-0.5   rounded-full">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" class="w-4">
                            <path d="M17.5798 9.71016C17.0765 9.57314 16.5468 9.5 16 9.5C13.4668 9.5 11.3002 11.0699 10.4202 13.2898M17.5798 9.71016C20.1271 10.4036 22 12.7331 22 15.5C22 18.8137 19.3137 21.5 16 21.5C14.4633 21.5 13.0615 20.9223 12 19.9722M17.5798 9.71016C17.851 9.02618 18 8.2805 18 7.5C18 4.18629 15.3137 1.5 12 1.5C8.68629 1.5 6 4.18629 6 7.5C6 8.2805 6.14903 9.02618 6.42018 9.71016M10.4202 13.2898C10.149 13.9738 10 14.7195 10 15.5C10 17.277 10.7725 18.8736 12 19.9722M10.4202 13.2898C8.59146 12.792 7.11029 11.451 6.42018 9.71016M6.42018 9.71016C3.87294 10.4036 2 12.7331 2 15.5C2 18.8137 4.68629 21.5 8 21.5C9.53671 21.5 10.9385 20.9223 12 19.9722" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" />
                        </svg>
                        {% if levels.count > 0 %}
                        {{ levels.count|thousand_separator }}+
                        {% endif %}
                    </span> 
                    classes registered already ... and counting...
                </small>
            </div>
            <h1 class="text-3xl lg:text-5xl font-bold font-sans">
                So you're a course delegate uhh... <br>
                for which level/group though?
            </h1>
            <p class="mt-4 text-center">
                Make man go see shege before say chopam. This life ehh ... e no fair!<br>
                How much am I even making? pfff
            </p>

            {% if levels.count < 1 %}
            <div class="relative -bottom-20 max-w-screen-lg flex flex-col items-center gap-8">
                <span href="{% url 'core:levels' %}"
                        class="px-6 py-2 rounded-full border border-dashed border-gray-500 text-gray-500 text-base">
                        classes coming soon
                    </span>
    
                <div class="grid grid-cols-12 items-center justify-center -space-x-3 w-full">
                    <img src="{% static 'core/images/cta2.jpg' %}" alt=""
                        class="col-span-4 h-full object-cover grayscale blur-[2px] -rotate-6 mt-10 shadow-lg rounded-xl ring-2 ring-offset-2 ring-primaryColor">
                    <img src="{% static 'core/images/cta1.jpg' %}" alt=""
                        class="col-span-4 h-full object-cover grayscale blur-[2px] rotate-3 shadow-lg rounded-xl ring-2 ring-offset-2 ring-secondaryColor">
                    <img src="{% static 'core/images/cta3.jpg' %}" alt=""
                        class="col-span-4 h-full object-cover grayscale blur-[2px] -rotate-3 mt-1 shadow-lg rounded-xl ring-2 ring-offset-2 ring-primaryColor">
                </div>
            </div>
            {% endif %}
        </div>

        <div class="absolute -top-8 blur-2xl opacity-50 w-full max-w-screen-xl h-16 bg-gradient-to-r from-primaryColor to-secondaryColor rounded-[300%]"></div>

        <section class="relative -top-32 px-14 py-10 grid grid-cols-12 gap-2 m-auto max-w-screen-xl">
            {% for level in levels %}
                {% if level.is_visible %}
                <a href="{% url 'core:dashboard' level_pk=level.id level_slug=level.slug %}" class="col-span-4 flex flex-col items-start gap-2 text-left shadow hover:shadow-lg rounded-2xl p-4 border outline outline-0 outline-transparent hover:outline hover:outline-1 hover:outline-darkColor border-darkColor bg-whiteColor hover:bg-[#ffecd5] transition-all duration-200 ease-linear">
                    <div class="leading-tight uppercase w-full">
                        {% if level.group %}
                        <h3 class="text-2xl font-bold">
                            {{ level.get_level_display }}, Group {{ level.group}}
                        </h3>
                        {% else %}
                        <h3 class="text-2xl font-bold">
                            {{ level.get_level_display }}
                        </h3>
                        {% endif %}
                        <div class="flex items-center justify-between text-gray-500">
                            <div class="flex items-center gap-2">
                                <small>{{ level.semester}} {{ level.year }}</small>
                                <small class="capitalize text-xs text-gray-400 px-2 py-0.5 rounded-full bg-gray-200">
                                    {{ level.created_at }}
                                </small>
                            </div>
                            <small> {{ level.department }} </small>
                        </div>
                    </div>
                    <hr class="w-full border-gray-500">
                    {% if level.about %}
                    <p class="text-base text-gray-500">
                        {{ level.about }}
                    </p>
                    {% else %}
                    <p class="text-base text-gray-500">
                        Welcome to this {{ level.get_level_display }}! Explore and discover more about it. 
                        Don't worry, it's a secret club. We only share the best memes here. 😄
                    </p>
                    {% endif %}
    
                    <div class="min-h-5 h-full"></div>
    
                    <div class="flex justify-between items-center w-full">
                        <div class="flex flex-col">
                            <div class="flex gap-2 text-secondaryColor">
                                {% if level.main_hall == 'Online' or level.main_hall == 'online' %}
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" class="w-5">
                                        <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="1.5" />
                                        <path d="M8 12C8 18 12 22 12 22C12 22 16 18 16 12C16 6 12 2 12 2C12 2 8 6 8 12Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" />
                                        <path d="M21 15H3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                        <path d="M21 9H3" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                    </svg>
                                  {% else %}
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" class="w-5">
                                        <path d="M2 22H22" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M18 9H14C11.518 9 11 9.518 11 12V22H21V12C21 9.518 20.482 9 18 9Z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" />
                                        <path d="M15 22H3V5C3 2.518 3.518 2 6 2H12C14.482 2 15 2.518 15 5V9" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" />
                                        <path d="M3 6H6M3 10H6M3 14H6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M15 13H17M15 16H17" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                                        <path d="M16 22L16 19" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                    </svg>
                                {% endif %}
                                <small>
                                    {{ level.main_hall }}
                                </small>
                            </div>
                            {% if level.secondary_hall %}
                            <div class="flex items-center gap-2">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" class="w-4">
                                    <path d="M16.9767 19.5C19.4017 17.8876 21 15.1305 21 12C21 7.02944 16.9706 3 12 3C11.3126 3 10.6432 3.07706 10 3.22302M16.9767 19.5V16M16.9767 19.5H20.5M7 4.51555C4.58803 6.13007 3 8.87958 3 12C3 16.9706 7.02944 21 12 21C12.6874 21 13.3568 20.9229 14 20.777M7 4.51555V8M7 4.51555H3.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                                <small class="text-xs">
                                    {{ level.secondary_hall }}
                                </small>
                            </div>
                            {% endif %}
                        </div>
    
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none" class="text-secondaryColor">
                            <path d="M9.00005 6C9.00005 6 15 10.4189 15 12C15 13.5812 9 18 9 18" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                        </svg>
                    </div>
                </a>
                {% endif %}                
            {% endfor %}
        </section>
    </div>
</main>

{% include "components/message.html" %}
{% endblock body %}

{% block javascript %}
{% endblock javascript %}