attendy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('summernote/', include('django_summernote.urls')),
    path('__reload__/', include("django_browser_reload.urls")),
    path('accounts/', include('allauth.urls')),
]

# Handlers for 404 and 500 errors
handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from .views import HomeView, DashboardView, CourseView, StudentView, LecturerView, TeachingRecordView, \
    TeachingRecordDetailView, CourseDetailView, StudentDetailView, LecturerDetailView, LecturerAddView, \
    StudentAddView, CourseAddView, CourseUpdateView, StudentUpdateView, LecturerUpdateView, \
    TeachingRecordUpdateView, LevelView, DashboardDetailView, AttendanceDetailView, AttendanceAddView, \
    CourseAttendanceAddView, AttendanceUpdateView, decode_qr, add_student_to_course_attendance, FeedbackView, \
    CourseRegistrationView, CourseStudentsPDFView, AttendancePDFView, TeachingRecordPDFView, StudentPDFView, \
    DownloadTemplateFileView, LecturerPDFView, CourseListPDFView, DashboardUpdateView

# Create your urls here
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    # Class levels URLs
    path('levels/', LevelView.as_view(), name='levels'),

    # Course URLs
    path('app/<int:level_pk>/courses/', CourseView.as_view(), name='courses'),
    path('app/<int:level_pk>/courses/pdf/', CourseListPDFView.as_view(), name='courses_pdf'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>', CourseDetailView.as_view(), name='course_detail'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>/pdf/', CourseStudentsPDFView.as_view(), name='course_pdf'),
    path('app/<int:level_pk>/courses/add/', CourseAddView.as_view(), name='course_add'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>/edit', CourseUpdateView.as_view(), name='course_update'),

    # Student URLs
    path('app/<int:level_pk>/students/', StudentView.as_view(), name='students'),
    path('app/<int:level_pk>/<str:model_name>/download-template/', DownloadTemplateFileView.as_view(), name='download_template'),
    path('app/<int:level_pk>/students/pdf/', StudentPDFView.as_view(), name='students_pdf'),
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/', StudentDetailView.as_view(), name='student_detail'),
    path('app/<int:level_pk>/students/add', StudentAddView.as_view(), name='student_add'),
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/edit/', StudentUpdateView.as_view(), name='student_update'),

    # Course Registration URLs
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/register-courses/', CourseRegistrationView.as_view(),
         name='course_registration'),

    # Lecturer URLs
    path('app/<int:level_pk>/lecturers/', LecturerView.as_view(), name='lecturers'),
    path('app/<int:level_pk>/lecturers/pdf/', LecturerPDFView.as_view(), name='lecturers_pdf'),
    path('app/<int:level_pk>/lecturers/<int:pk>/<slug:slug>/', LecturerDetailView.as_view(),
         name='lecturer_detail'),
    path('app/<int:level_pk>/lecturers/add/', LecturerAddView.as_view(), name='lecturer_add'),
    path('app/<int:level_pk>/lecturers/<int:pk>/<slug:slug>/edit', LecturerUpdateView.as_view(),
         name='lecturer_update'),

    # Teaching Record URLs
    path('app/<int:level_pk>/records/', TeachingRecordView.as_view(), name='records'),
    path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/', TeachingRecordDetailView.as_view(),
         name='record_detail'),
path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/pdf/', TeachingRecordPDFView.as_view(),
         name='record_pdf'),
    path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/edit', TeachingRecordUpdateView.as_view(),
         name='record_update'),

    # Dashboard URLs
    path('app/<int:level_pk>/<slug:level_slug>/', DashboardView.as_view(), name='dashboard'),
    path('app/<int:level_pk>/<slug:level_slug>/overview/', DashboardDetailView.as_view(), name='dashboard_detail'),
    path('app/<int:level_pk>/<slug:level_slug>/overview/update/', DashboardUpdateView.as_view(), name='dashboard_update'),

    # Attendance URLs
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/', AttendanceDetailView.as_view(),
         name='attendance_detail'),
path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/pdf/', AttendancePDFView.as_view(),
         name='attendance_pdf'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/edit/', AttendanceUpdateView.as_view(),
         name='attendance_update'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/add/', AttendanceAddView.as_view(), name='attendance_add'),

    # Enrollment URLs
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/admit/', CourseAttendanceAddView.as_view(),
         name='enroll_add'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/scan/', decode_qr, name='decode_qr'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/scan/admit/', add_student_to_course_attendance,
         name='add_student_to_course_attendance'),

    # Feedback URLs
    path('app/feedback/', FeedbackView.as_view(), name='feedback'), 
]

core/views.py
import csv
import json
import os
import random
from collections import defaultdict
from datetime import timedelta, datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Q, Count, Sum
from django.http import JsonResponse, FileResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.html import format_html
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, View
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image

from .forms import CourseForm, LecturerForm, StudentForm, TeachingRecordForm, AttendanceForm, CourseAttendanceForm, \
    FeedbackForm, ClassLevelForm
from .mixins import CommonContextMixin, ClassLevelAccessMixin
from .models import Course, Student, Lecturer, TeachingRecord, CourseDelegate, CourseAttendance, \
    ClassLevel, Attendance, ClassLevelUser, Feedback, CourseRegistration
from .utils import group_model_items_by_week, get_faqs, get_quotes, decode_data, date_formatter, time_formatter, \
    short_date_formatter, parse_html_to_flowables


# Create your views here.
class HomeView(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['levels_count'] = ClassLevel.objects.all().count()
        context['course_attendance_count'] = Attendance.objects.all().count()
        context['courses_count'] = Course.objects.all().count()
        context['lecturers_count'] = Lecturer.objects.all().count()
        context['students_count'] = Student.objects.all().count()
        context['faqs'] = get_faqs
        context['current_year'] = datetime.now().year
        return context


class LevelView(LoginRequiredMixin, ListView):
    model = ClassLevel
    template_name = 'core/dashboard/levels.html'
    context_object_name = 'levels'
    paginate_by = 25

    def get_queryset(self):
        if self.request.user.is_superuser:
            return ClassLevel.objects.all().order_by('year', 'semester')
        return ClassLevel.objects.filter(class_level_users__user=self.request.user).order_by('year', 'semester')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_year'] = datetime.now().year
        return context


# Dashboard views
def group_items_by_week(attendances):
    grouped_attendances = defaultdict(list)
    for attendance in attendances.order_by('created_at'):
        # Calculate the start of the week (Monday) for each item
        week_start = attendance.created_at - timedelta(days=attendance.created_at.weekday())
        week_end = week_start + timedelta(days=6)

        # Format the week range as "Mon 19 Aug - Sun 25 Aug"
        week_range = f"{week_start.strftime('%a %d %b')} - {week_end.strftime('%a %d %b %Y')}"

        # Group items by this week range
        grouped_attendances[week_range].append(attendance)

    return dict(grouped_attendances)


# core/views.py
class DashboardView(LoginRequiredMixin, CommonContextMixin, ClassLevelAccessMixin, DetailView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard.html'
    context_object_name = 'level'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        grouped_attendances = group_items_by_week(
            Attendance.objects.filter(class_level=self.kwargs['level_pk'])
        )
        for week, attendances in grouped_attendances.items():
            for attendance in attendances:
                attendance.course_delegate = CourseDelegate.objects.filter(course=attendance.course,
                                                                           role='delegate').first()
                attendance.course_assistant = CourseDelegate.objects.filter(course=attendance.course,
                                                                            role='assistant').first()
                attendance.enrollment_count = CourseAttendance.objects.filter(attendance=attendance).count()
        context['grouped_attendances'] = dict(grouped_attendances)

        # Calculate number of attendances per course, including courses with zero attendance
        courses = Course.objects.filter(class_level=self.kwargs['level_pk'])
        course_attendance_counts = courses.annotate(count=Count('course_attendance')).values('title', 'count').order_by(
            'title')
        context['course_attendance_counts'] = json.dumps(list(course_attendance_counts))

        return context


class DashboardDetailView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard_details.html'
    context_object_name = 'level'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = ClassLevelUser.objects.filter(class_level=self.kwargs['level_pk'])
        return context


class DashboardUpdateView(LoginRequiredMixin, CommonContextMixin, UpdateView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard_update.html'
    context_object_name = 'form'
    form_class = ClassLevelForm

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_success_url(self):
        return reverse_lazy('core:dashboard_detail', kwargs={'level_pk': self.kwargs['level_pk'], 'level_slug': self.kwargs['level_slug']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['class_level'] = self.get_object()
        return context

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Class info updated successfully.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'An error occurred while updating class info. Please try again.')
        return super().form_invalid(form)

class AttendanceDetailView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = Attendance
    template_name = 'core/attendance/attendance_details.html'
    context_object_name = 'attendance'

    def get_object(self, queryset=None):
        return get_object_or_404(
            self.model,
            class_level=self.kwargs['level_pk'],
            class_level__slug=self.kwargs['level_slug'],
            id=self.kwargs['pk']
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course_delegates'] = CourseDelegate.objects.filter(
            course=self.object.course,
            student__is_delegate=True
        )
        context['enrollments'] = CourseAttendance.objects.filter(attendance=self.object,
                                                                 attendance__class_level=self.kwargs[
                                                                     'level_pk']).order_by('created_at')
        return context

    def post(self, request, *args, **kwargs):
        if 'delete_enrollment' in request.POST:
            enrollment_id = request.POST.get('enrollment_id')
            enrollment = CourseAttendance.objects.get(id=enrollment_id)
            enrollment.delete()
            message = format_html(
                '<strong>{}</strong> was removed successfully.',
                enrollment.student.name
            )
            messages.success(request, message)
        return self.get(request, *args, **kwargs)


class AttendancePDFView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = Attendance
    template_name = 'core/attendance/attendance_details.html'
    context_object_name = 'attendance'

    def get(self, request, *args, **kwargs):
        attendance = self.get_object()
        course_delegate = CourseDelegate.objects.filter(course=attendance.course, student__is_delegate=True,
                                                        role='delegate')
        enrollments = CourseAttendance.objects.filter(attendance=self.get_object(),
                                                      attendance__class_level=self.kwargs[
                                                          'level_pk']).order_by('created_at')

        # Generate PDF file path
        filename = f"{attendance.course.title}_attendance_sheet_{attendance.course_date}.pdf"
        pdf_folder_path = os.path.join(settings.MEDIA_ROOT, 'attendance_sheets')
        os.makedirs(pdf_folder_path, exist_ok=True)
        pdf_file_path = os.path.join(pdf_folder_path, filename)

        doc = SimpleDocTemplate(pdf_file_path, title=filename, pagesize=A4, rightMargin=24, leftMargin=24, topMargin=20,
                                bottomMargin=18)
        elements = []

        # Add the image at the top
        image_path = str(settings.BASE_DIR / 'static/core/images/ictu_logo.png')
        logo = Image(image_path)
        logo.drawHeight = 1.25 * inch
        logo.drawWidth = 1.25 * inch
        elements.append(logo)

        styles = getSampleStyleSheet()
        styles['Normal'].leading = 20

templates/core/base.html
{% load static tailwind_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en" class="scroll-smooth bg-whiteColor">

<head>
    <!-- og meta tags -->
    {% block meta_tags %}

    {% endblock meta_tags %}

    <!-- Title and Meta tags -->
    {% include "components/meta.html" %}

    {# Icons ~ HugeIcons, Free Stroke rounded icons. #}
    <!-- SVG codes of icons are directly obtained (copied) from https://hugeicons.com/icons -->

    {# CSS: Tailwind, Custom #}
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
    {% block styles %}{% endblock styles %}

</head>

<body class="font-sans text-lg text-darkColor bg-whiteColor {% block body_styles %}{% endblock body_styles %}">

    {# Header of the page #}
    {% block header %}

    {% endblock header %}

    {# Body of the page #}
    {% block body %}

    {% endblock body %}

    {# Footer of the page #}
    {% block footer %}

    {% endblock footer %}

    {# JS and Additional javascript #}
    {% block javascript %}

    {% endblock javascript %}

</body>

</html>

templates/core/base_app.html
{% load static tailwind_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en" class="scroll-smooth bg-whiteColor">

<head>
    <!-- og meta tags -->
    {% block meta_tags %}

    {% endblock meta_tags %}

    <!-- Title and Meta tags -->
    {% include "components/meta.html" %}

    {# Icons ~ HugeIcons, Free Stroke rounded icons. #}
    <!-- SVG codes of icons are directly obtained (copied) from https://hugeicons.com/icons -->

    {# CSS: Tailwind, Custom #}
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'core/css/app.css' %}">
    {% block extra_styles %}{% endblock extra_styles %}

    <!-- Chart.js -->
    <script src="{% static 'core/js/chart-v4.4.4.js' %}"></script>

</head>

<body class="font-sans text-lg text-darkColor bg-whiteColor {% block body_styles %}{% endblock body_styles %}">

    {% block header %}

    {% endblock header %}

    {% block body %}

    {% endblock %}

    {# JS and Additional javascript #}
    {% block javascript %}

    {% endblock javascript %}
    <!-- Flowbite JS script -->
    <script src="{% static 'core/js/flowbite.js' %}"></script>
</body>

</html>

templates/core/teaching_record_detail.html
{% extends 'core/base_app.html' %}
{% load static %}
{% load tailwind_tags %}
{% load custom_date_formatter %}

{# Title of the page #}
{% block title %} {{ record.course.title }} {% endblock %}

{% block extra_styles %}
<style>
    .record-content ul {
        list-style-type: disc;
        padding-left: 1.5rem;
    }

    .record-content ol {
        list-style-type: decimal;
        padding-left: 1.5rem;
    }

    .record-content h1,
    .record-content h2,
    .record-content h3,
    .record-content h4,
    .record-content h5,
    .record-content h6 {
        font-size: 1.5rem;
        font-weight: bold;
        margin-top: 1.5rem;
        margin-bottom: 0.5rem;
    }

    .record-content a {
        text-decoration: underline;
        color: #4285F4;
    }
</style>
{% endblock extra_styles %}

{# Body styles #}
{% block body_styles %}
{% endblock body_styles %}

{# Header of the page #}
{% block header %}
{% include "components/header_app.html" %}
{% endblock header %}

{# Body of the page #}
{% block body %}
<div class="relative p-4 md:ml-64">
    <div class="flex flex-col gap-4 items-start justify-center w-full mt-14">
        <div class="flex flex-col gap-1">
            <small>
                <a href="{% url 'core:records' %}" class="text-secondaryColor">Teaching records</a> /
            </small>
            <h2 class="text-3xl">
                {{ record.course.code }} {{ record.course.title }}
            </h2>
            <small class="flex items-center gap-4">
                <span class="text-darkColor flex gap-1 px-2.5 rounded-xl bg-darkColor/5">
                    <span class="text-darkColor/50">Quality assurance: </span>
                    {% if record.quality_assurance == 'Approved' %}
                    <span class="text-success">{{ record.quality_assurance }}</span>
                    {% else %}
                    <span class="text-danger">{{ record.quality_assurance }}</span>
                    {% endif %}
                </span>

                <span class="text-darkColor flex gap-1 px-2.5 rounded-xl bg-darkColor/5">
                    <span class="text-darkColor/50">Last update: </span>
                    {{ record.updated_at|format_date }}
                </span>
            </small>
        </div>

        <div class="grid grid-cols-12 gap-2">
            <div class="col-span-full lg:col-span-8">
                <h3 class="block text-xl text-secondaryColor font-medium">Lessons and Brief Content/Assignments</h3>
                <div class="record-content">
                    {{ record.description|safe }}
                </div>
            </div>

            <div class="col-span-full lg:col-span-3 lg:col-start-10">
                <div class="flex flex-col gap-2 w-full">

                    <div class="flex flex-col items-start py-2 px-4 rounded-2xl bg-secondaryColor/10">
                        <small class="text-darkColor/50 text-sm">Lecturer:</small>
                        <span class="text-darkColor"> {{ record.lecturer.name }} </span>
                    </div>

                    <div class="flex flex-col items-start py-2 px-4 rounded-2xl bg-secondaryColor/10">
                        <small class="text-darkColor/50 text-sm">Course delegate:</small>
                        <span class="text-darkColor"> {{ course_delegate.student.name }} </span>
                    </div>

                    <div class="flex flex-col items-start gap-0.5 py-2 px-4 rounded-2xl bg-secondaryColor/10">
                        <small class="text-darkColor/50 text-sm">Start - Finish time:</small>
                        <span class="text-darkColor"> {{ record.course.start_time }} ~ {{ record.course.end_time }}
                        </span>
                    </div>

                    <div class="flex flex-col items-start gap-0.5 py-2 px-4 rounded-2xl bg-secondaryColor/10">
                        <small class="text-darkColor/50 text-sm">Duration:</small>
                        <span class="text-darkColor"> {{ record.course.duration }} </span>
                    </div>

                    <div class="flex flex-col items-start gap-0.5 py-2 px-4 rounded-2xl bg-secondaryColor/10">
                        <small class="text-darkColor/50 text-sm">Semester:</small>
                        <span class="text-darkColor"> {{ record.course.semester }} {{ record.course.year }} </span>
                    </div>

                    <div class="flex flex-col items-start gap-0.5 py-2 px-4 rounded-2xl bg-secondaryColor/10">
                        <small class="text-darkColor/50 text-sm">Number of students:</small>
                        <span class="text-darkColor">
                            {% if enrollments > 0 %}
                            {{ enrollments }}
                            {% else %}
                            No students enrolled.
                            {% endif %}
                        </span>
                    </div>

                    <div class="flex flex-col items-start gap-0.5 py-2 px-4 rounded-2xl bg-secondaryColor/10">
                        <small class="text-darkColor/50 text-sm">Date:</small>
                        <span class="text-darkColor"> {{ record.created_at|format_date }} </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="flex gap-2">
            <a href="" class="flex items-center gap-2 py-2 px-4 rounded-xl text-whiteColor bg-primaryColor hover:bg-blue-950 transition-all duration-300 ease-linear">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none">
                    <path d="M20 13V10.6569C20 9.83935 20 9.4306 19.8478 9.06306C19.6955 8.69552 19.4065 8.40649 18.8284 7.82843L14.0919 3.09188C13.593 2.593 13.3436 2.34355 13.0345 2.19575C12.9702 2.165 12.9044 2.13772 12.8372 2.11401C12.5141 2 12.1614 2 11.4558 2C8.21082 2 6.58831 2 5.48933 2.88607C5.26731 3.06508 5.06508 3.26731 4.88607 3.48933C4 4.58831 4 6.21082 4 9.45584V13M13 2.5V3C13 5.82843 13 7.24264 13.8787 8.12132C14.7574 9 16.1716 9 19 9H19.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M19.75 16H17.25C16.6977 16 16.25 16.4477 16.25 17V19M16.25 19V22M16.25 19H19.25M4.25 22V19.5M4.25 19.5V16H6C6.9665 16 7.75 16.7835 7.75 17.75C7.75 18.7165 6.9665 19.5 6 19.5H4.25ZM10.25 16H11.75C12.8546 16 13.75 16.8954 13.75 18V20C13.75 21.1046 12.8546 22 11.75 22H10.25V16Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
                Print record
            </a>

            <a href="" class="flex items-center gap-2 py-2 px-4 rounded-xl text-whiteColor bg-primaryColor hover:bg-blue-950 transition-all duration-300 ease-linear">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none">
                    <path d="M10.2892 21.9614H9.39111C6.14261 21.9614 4.51836 21.9614 3.50918 20.9363C2.5 19.9111 2.5 18.2612 2.5 14.9614V9.96139C2.5 6.66156 2.5 5.01165 3.50918 3.98653C4.51836 2.9614 6.14261 2.9614 9.39111 2.9614H12.3444C15.5929 2.9614 17.4907 3.01658 18.5 4.04171C19.5092 5.06683 19.5 6.66156 19.5 9.96139V11.1478" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M15.9453 2V4M10.9453 2V4M5.94531 2V4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                    <path d="M7 15H11M7 10H15" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                    <path opacity="0.93" d="M20.7598 14.8785C19.8544 13.8641 19.3112 13.9245 18.7076 14.1056C18.2851 14.166 16.8365 15.8568 16.2329 16.3952C15.2419 17.3743 14.2464 18.3823 14.1807 18.5138C13.9931 18.8188 13.8186 19.3592 13.7341 19.963C13.5771 20.8688 13.3507 21.8885 13.6375 21.9759C13.9242 22.0632 14.7239 21.8954 15.6293 21.7625C16.2329 21.6538 16.6554 21.533 16.9572 21.3519C17.3797 21.0983 18.1644 20.2046 19.5164 18.8761C20.3644 17.9833 21.1823 17.3664 21.4238 16.7626C21.6652 15.8568 21.3031 15.3737 20.7598 14.8785Z" stroke="currentColor" stroke-width="1.5" />
                </svg>
                Edit record
            </a>

            <a href="" title="Delete record" class="flex items-center gap-2 py-2 px-2.5 rounded-xl text-whiteColor bg-danger hover:bg-red-600 transition-all duration-300 ease-linear">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none">
                    <path d="M19.5 5.5L18.8803 15.5251C18.7219 18.0864 18.6428 19.3671 18.0008 20.2879C17.6833 20.7431 17.2747 21.1273 16.8007 21.416C15.8421 22 14.559 22 11.9927 22C9.42312 22 8.1383 22 7.17905 21.4149C6.7048 21.1257 6.296 20.7408 5.97868 20.2848C5.33688 19.3626 5.25945 18.0801 5.10461 15.5152L4.5 5.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                    <path d="M9 11.7349H15" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                    <path d="M10.5 15.6543H13.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                    <path d="M3 5.5H21M16.0555 5.5L15.3729 4.09173C14.9194 3.15626 14.6926 2.68852 14.3015 2.39681C14.2148 2.3321 14.1229 2.27454 14.0268 2.2247C13.5937 2 13.0739 2 12.0343 2C10.9686 2 10.4358 2 9.99549 2.23412C9.89791 2.28601 9.80479 2.3459 9.7171 2.41317C9.32145 2.7167 9.10044 3.20155 8.65842 4.17126L8.05273 5.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                </svg>
            </a>
        </div>
    </div>
</div>
{% endblock body %}