attendy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('summernote/', include('django_summernote.urls')),
    path('__reload__/', include("django_browser_reload.urls")),
    path('accounts/', include('allauth.urls')),
]

# Handlers for 404 and 500 errors
handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from .views import HomeView, DashboardView, CourseView, StudentView, LecturerView, TeachingRecordView, \
    TeachingRecordDetailView, CourseDetailView, StudentDetailView, LecturerDetailView, LecturerAddView, \
    StudentAddView, CourseAddView, CourseUpdateView, StudentUpdateView, LecturerUpdateView, \
    TeachingRecordUpdateView, LevelView, DashboardDetailView, AttendanceDetailView, AttendanceAddView, \
    CourseAttendanceAddView, AttendanceUpdateView, decode_qr, add_student_to_course_attendance, FeedbackView, \
    CourseRegistrationView, CourseStudentsPDFView, AttendancePDFView, TeachingRecordPDFView, StudentPDFView, \
    DownloadTemplateFileView, LecturerPDFView, CourseListPDFView, DashboardUpdateView

# Create your urls here
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    # Class levels URLs
    path('levels/', LevelView.as_view(), name='levels'),

    # Course URLs
    path('app/<int:level_pk>/courses/', CourseView.as_view(), name='courses'),
    path('app/<int:level_pk>/courses/pdf/', CourseListPDFView.as_view(), name='courses_pdf'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>', CourseDetailView.as_view(), name='course_detail'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>/pdf/', CourseStudentsPDFView.as_view(), name='course_pdf'),
    path('app/<int:level_pk>/courses/add/', CourseAddView.as_view(), name='course_add'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>/edit', CourseUpdateView.as_view(), name='course_update'),

    # Student URLs
    path('app/<int:level_pk>/students/', StudentView.as_view(), name='students'),
    path('app/<int:level_pk>/<str:model_name>/download-template/', DownloadTemplateFileView.as_view(), name='download_template'),
    path('app/<int:level_pk>/students/pdf/', StudentPDFView.as_view(), name='students_pdf'),
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/', StudentDetailView.as_view(), name='student_detail'),
    path('app/<int:level_pk>/students/add', StudentAddView.as_view(), name='student_add'),
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/edit/', StudentUpdateView.as_view(), name='student_update'),

    # Course Registration URLs
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/register-courses/', CourseRegistrationView.as_view(),
         name='course_registration'),

    # Lecturer URLs
    path('app/<int:level_pk>/lecturers/', LecturerView.as_view(), name='lecturers'),
    path('app/<int:level_pk>/lecturers/pdf/', LecturerPDFView.as_view(), name='lecturers_pdf'),
    path('app/<int:level_pk>/lecturers/<int:pk>/<slug:slug>/', LecturerDetailView.as_view(),
         name='lecturer_detail'),
    path('app/<int:level_pk>/lecturers/add/', LecturerAddView.as_view(), name='lecturer_add'),
    path('app/<int:level_pk>/lecturers/<int:pk>/<slug:slug>/edit', LecturerUpdateView.as_view(),
         name='lecturer_update'),

    # Teaching Record URLs
    path('app/<int:level_pk>/records/', TeachingRecordView.as_view(), name='records'),
    path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/', TeachingRecordDetailView.as_view(),
         name='record_detail'),
path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/pdf/', TeachingRecordPDFView.as_view(),
         name='record_pdf'),
    path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/edit', TeachingRecordUpdateView.as_view(),
         name='record_update'),

    # Dashboard URLs
    path('app/<int:level_pk>/<slug:level_slug>/', DashboardView.as_view(), name='dashboard'),
    path('app/<int:level_pk>/<slug:level_slug>/overview/', DashboardDetailView.as_view(), name='dashboard_detail'),
    path('app/<int:level_pk>/<slug:level_slug>/overview/update/', DashboardUpdateView.as_view(), name='dashboard_update'),

    # Attendance URLs
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/', AttendanceDetailView.as_view(),
         name='attendance_detail'),
path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/pdf/', AttendancePDFView.as_view(),
         name='attendance_pdf'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/edit/', AttendanceUpdateView.as_view(),
         name='attendance_update'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/add/', AttendanceAddView.as_view(), name='attendance_add'),

    # Enrollment URLs
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/admit/', CourseAttendanceAddView.as_view(),
         name='enroll_add'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/scan/', decode_qr, name='decode_qr'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/scan/admit/', add_student_to_course_attendance,
         name='add_student_to_course_attendance'),

    # Feedback URLs
    path('app/feedback/', FeedbackView.as_view(), name='feedback'), 
]

core/views.py
import csv
import json
import os
import random
from collections import defaultdict
from datetime import timedelta, datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Q, Count, Sum
from django.http import JsonResponse, FileResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.html import format_html
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, View
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image

from .forms import CourseForm, LecturerForm, StudentForm, TeachingRecordForm, AttendanceForm, CourseAttendanceForm, \
    FeedbackForm, ClassLevelForm
from .mixins import CommonContextMixin, ClassLevelAccessMixin
from .models import Course, Student, Lecturer, TeachingRecord, CourseDelegate, CourseAttendance, \
    ClassLevel, Attendance, ClassLevelUser, Feedback, CourseRegistration
from .utils import group_model_items_by_week, get_faqs, get_quotes, decode_data, date_formatter, time_formatter, \
    short_date_formatter, parse_html_to_flowables


# Create your views here.
class HomeView(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['levels_count'] = ClassLevel.objects.all().count()
        context['course_attendance_count'] = Attendance.objects.all().count()
        context['courses_count'] = Course.objects.all().count()
        context['lecturers_count'] = Lecturer.objects.all().count()
        context['students_count'] = Student.objects.all().count()
        context['faqs'] = get_faqs
        context['current_year'] = datetime.now().year
        return context


class LevelView(LoginRequiredMixin, ListView):
    model = ClassLevel
    template_name = 'core/dashboard/levels.html'
    context_object_name = 'levels'
    paginate_by = 25

    def get_queryset(self):
        if self.request.user.is_superuser:
            return ClassLevel.objects.all().order_by('year', 'semester')
        return ClassLevel.objects.filter(class_level_users__user=self.request.user).order_by('year', 'semester')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_year'] = datetime.now().year
        return context


# Dashboard views
def group_items_by_week(attendances):
    grouped_attendances = defaultdict(list)
    for attendance in attendances.order_by('created_at'):
        # Calculate the start of the week (Monday) for each item
        week_start = attendance.created_at - timedelta(days=attendance.created_at.weekday())
        week_end = week_start + timedelta(days=6)

        # Format the week range as "Mon 19 Aug - Sun 25 Aug"
        week_range = f"{week_start.strftime('%a %d %b')} - {week_end.strftime('%a %d %b %Y')}"

        # Group items by this week range
        grouped_attendances[week_range].append(attendance)

    return dict(grouped_attendances)


# core/views.py
class DashboardView(LoginRequiredMixin, CommonContextMixin, ClassLevelAccessMixin, DetailView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard.html'
    context_object_name = 'level'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        grouped_attendances = group_items_by_week(
            Attendance.objects.filter(class_level=self.kwargs['level_pk'])
        )
        for week, attendances in grouped_attendances.items():
            for attendance in attendances:
                attendance.course_delegate = CourseDelegate.objects.filter(course=attendance.course,
                                                                           role='delegate').first()
                attendance.course_assistant = CourseDelegate.objects.filter(course=attendance.course,
                                                                            role='assistant').first()
                attendance.enrollment_count = CourseAttendance.objects.filter(attendance=attendance).count()
        context['grouped_attendances'] = dict(grouped_attendances)

        # Calculate number of attendances per course, including courses with zero attendance
        courses = Course.objects.filter(class_level=self.kwargs['level_pk'])
        course_attendance_counts = courses.annotate(count=Count('course_attendance')).values('title', 'count').order_by(
            'title')
        context['course_attendance_counts'] = json.dumps(list(course_attendance_counts))

        return context


class DashboardDetailView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard_details.html'
    context_object_name = 'level'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = ClassLevelUser.objects.filter(class_level=self.kwargs['level_pk'])
        return context


class DashboardUpdateView(LoginRequiredMixin, CommonContextMixin, UpdateView):
    model = ClassLevel
    template_name = 'core/dashboard/dashboard_update.html'
    context_object_name = 'form'
    form_class = ClassLevelForm

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, id=self.kwargs['level_pk'], slug=self.kwargs['level_slug'])

    def get_success_url(self):
        return reverse_lazy('core:dashboard_detail', kwargs={'level_pk': self.kwargs['level_pk'], 'level_slug': self.kwargs['level_slug']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['class_level'] = self.get_object()
        return context

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Class info updated successfully.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'An error occurred while updating class info. Please try again.')
        return super().form_invalid(form)

class AttendanceDetailView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = Attendance
    template_name = 'core/attendance/attendance_details.html'
    context_object_name = 'attendance'

    def get_object(self, queryset=None):
        return get_object_or_404(
            self.model,
            class_level=self.kwargs['level_pk'],
            class_level__slug=self.kwargs['level_slug'],
            id=self.kwargs['pk']
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course_delegates'] = CourseDelegate.objects.filter(
            course=self.object.course,
            student__is_delegate=True
        )
        context['enrollments'] = CourseAttendance.objects.filter(attendance=self.object,
                                                                 attendance__class_level=self.kwargs[
                                                                     'level_pk']).order_by('created_at')
        return context

    def post(self, request, *args, **kwargs):
        if 'delete_enrollment' in request.POST:
            enrollment_id = request.POST.get('enrollment_id')
            enrollment = CourseAttendance.objects.get(id=enrollment_id)
            enrollment.delete()
            message = format_html(
                '<strong>{}</strong> was removed successfully.',
                enrollment.student.name
            )
            messages.success(request, message)
        return self.get(request, *args, **kwargs)


class AttendancePDFView(LoginRequiredMixin, CommonContextMixin, DetailView):
    model = Attendance
    template_name = 'core/attendance/attendance_details.html'
    context_object_name = 'attendance'

    def get(self, request, *args, **kwargs):
        attendance = self.get_object()
        course_delegate = CourseDelegate.objects.filter(course=attendance.course, student__is_delegate=True,
                                                        role='delegate')
        enrollments = CourseAttendance.objects.filter(attendance=self.get_object(),
                                                      attendance__class_level=self.kwargs[
                                                          'level_pk']).order_by('created_at')

        # Generate PDF file path
        filename = f"{attendance.course.title}_attendance_sheet_{attendance.course_date}.pdf"
        pdf_folder_path = os.path.join(settings.MEDIA_ROOT, 'attendance_sheets')
        os.makedirs(pdf_folder_path, exist_ok=True)
        pdf_file_path = os.path.join(pdf_folder_path, filename)

        doc = SimpleDocTemplate(pdf_file_path, title=filename, pagesize=A4, rightMargin=24, leftMargin=24, topMargin=20,
                                bottomMargin=18)
        elements = []

        # Add the image at the top
        image_path = str(settings.BASE_DIR / 'static/core/images/ictu_logo.png')
        logo = Image(image_path)
        logo.drawHeight = 1.25 * inch
        logo.drawWidth = 1.25 * inch
        elements.append(logo)

        styles = getSampleStyleSheet()
        styles['Normal'].leading = 20

templates/core/enrollment/course_attendance_add.html
{% extends 'core/base_app.html' %}
{% load static %}
{% load tailwind_tags %}
{% load custom_date_formatter duration_formatter %}

{# Title of the page #}
{% block title %} Admit student into attendance {% endblock %}

{% block extra_styles %}
    <style>
        #lect_img {
            background: linear-gradient(170deg, rgba(0, 0, 0, 0.9) 25%, rgba(0, 0, 0, 0.1) 75%), url("{% static 'core/images/attendance.jpg' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }
    </style>
{% endblock extra_styles %}

{# Header of the page #}
{% block header %}
    {% include "components/header_app.html" %}
{% endblock header %}

{# Body of the page #}
{% block body %}
    <div class="relative p-4 md:ml-64">
        <div class="flex flex-col gap-4 items-start justify-center w-full mt-14">
            <div class="grid grid-cols-12 items-center justify-center gap-2 w-full">
                <div class="col-start-1 lg:col-start-2 col-span-full lg:col-span-4 flex flex-col gap-4">
                    <div class="flex flex-col gap-2">
                        <h2 class="text-2xl">Admit a student into attendance</h2>
                        <p class="text-sm">
                            Manually add a student into the current attendance list.
                            You can only add student who registered this course or who are part of this class.
                        </p>
                    </div>

                    <form action="{% url 'core:enroll_add' level_pk=level.id level_slug=level.slug pk=attendance.id %}" method="post" class="max-w-sm w-full">
                        {% csrf_token %}

                        <!-- Display non fields errors -->
                        {% if form.non_field_errors %}
                            <small class="text-sm text-danger bg-danger/10 rounded-xl px-2 py-1">
                                {% for error in form.non_field_errors %}
                                    {{ error }}
                                {% endfor %}
                            </small>
                        {% endif %}

                        <div class="flex flex-col gap-2">
                            {# Student field #}
                            <div class="">
                                <label for="{{ form.student.label }}" class="ps-4 text-xs text-gray-500"> {{ form.student.label }} </label>
                                <div class="relative">
                                    <div class="absolute inset-y-0 start-0 flex items-center ps-2.5 pointer-events-none">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none">
                                            <path d="M6.57757 15.4816C5.1628 16.324 1.45336 18.0441 3.71266 20.1966C4.81631 21.248 6.04549 22 7.59087 22H16.4091C17.9545 22 19.1837 21.248 20.2873 20.1966C22.5466 18.0441 18.8372 16.324 17.4224 15.4816C14.1048 13.5061 9.89519 13.5061 6.57757 15.4816Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                            <path d="M16.5 6.5C16.5 8.98528 14.4853 11 12 11C9.51472 11 7.5 8.98528 7.5 6.5C7.5 4.01472 9.51472 2 12 2C14.4853 2 16.5 4.01472 16.5 6.5Z" stroke="currentColor" stroke-width="1.5" />
                                        </svg>
                                    </div>
                                    {{ form.student }}
                                </div>
            
                                {% if form.student.errors %}
                                <small class="ps-4 text-sm text-danger">
                                    {% for error in form.student.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </small>
                                {% endif %}
                            </div>

                            {# Attendance field #}
                            <div class="">
                                <label for="{{ form.attendance.label }}"
                                       class="ps-4 text-xs text-gray-500"> {{ form.attendance.label }} </label>
                                <div class="relative">
                                    <div class="absolute inset-y-0 start-0 flex items-center ps-2.5 pointer-events-none">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none">
                                            <path d="M3.5 9V14C3.5 17.7712 3.5 19.6569 4.67157 20.8284C5.84315 22 7.72876 22 11.5 22H12.5C16.2712 22 18.1569 22 19.3284 20.8284C20.5 19.6569 20.5 17.7712 20.5 14V10C20.5 6.22876 20.5 4.34315 19.3284 3.17157C18.1569 2 16.2712 2 12.5 2H12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                            <path d="M13.5 17H17.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                            <path d="M13.5 7H17.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                            <path d="M13.5 12H17.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                            <path d="M6.5 16.5C6.5 16.5 7.46758 16.7672 8 18C8 18 9 15 11 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                            <path d="M10 5H3.5M10 5C10 4.15973 7.67332 2.58984 7.08333 2M10 5C10 5.84027 7.67331 7.41016 7.08333 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                                        </svg>
                                    </div>
                                    {{ form.attendance }}
                                </div>

                                {% if form.attendance.errors %}
                                    <small class="ps-4 text-sm text-danger">
                                        {% for error in form.attendance.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </small>
                                {% endif %}
                            </div>


                            {# Submit button #}
                            <div class="text-whiteColor">
                                <button type="submit"
                                        class="block mb-2 focus:outline-none rounded-2xl w-full px-5 py-2 text-center bg-primaryColor hover:bg-blue-950 focus:ring-2 focus:ring-secondaryColor focus:ring-offset-1 transition-all duration-300 ease-in-out">
                                    Admit student
                                </button>
                                <small class="text-gray-500 text-xs">
                                    This course attendance accounts for <strong>{{ level.semester }} {{ level.year }}</strong>
                                </small>
                            </div>
                        </div>
                    </form>
                </div>

                <div id="lect_img" class="relative lg:col-start-8 col-span-full lg:col-span-4 h-80 lg:h-screen">
                    <blockquote
                            class="flex flex-col gap-2 text-[16px] leading-tight text-whiteColor p-4 text-left max-w-64">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none"
                             class="text-secondaryColor">
                            <path d="M5.07579 17C4.08939 4.54502 12.9123 1.0121 19.9734 2.22417C20.2585 6.35185 18.2389 7.89748 14.3926 8.61125C15.1353 9.38731 16.4477 10.3639 16.3061 11.5847C16.2054 12.4534 15.6154 12.8797 14.4355 13.7322C11.8497 15.6004 8.85421 16.7785 5.07579 17Z"
                                  stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                                  stroke-linejoin="round"/>
                            <path d="M4 22C4 15.5 7.84848 12.1818 10.5 10" stroke="currentColor" stroke-width="1.5"
                                  stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        There's this one thing about class attendance: you can show up every day, yet somehow the teacher will only notice the one day
                        you decide to skip.
                        <cite class="block font-semibold mt-2 text-secondaryColor">ChatGPT</cite>
                    </blockquote>
                    <img src="{% static 'core/images/logo-shapes.svg' %}" alt="Attendy shapes"
                         class="w-20 absolute bottom-3 right-3">
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

{# Additional javascript #}
{% block javascript %}
{% endblock javascript %}