attendy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('summernote/', include('django_summernote.urls')),
    path('__reload__/', include("django_browser_reload.urls")),
    path('accounts/', include('allauth.urls')),
]

# Handlers for 404 and 500 errors
handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from .views import HomeView, DashboardView, CourseView, StudentView, LecturerView, TeachingRecordView, \
    TeachingRecordDetailView, CourseDetailView, StudentDetailView, LecturerDetailView, LecturerAddView, \
    StudentAddView, CourseAddView, CourseUpdateView, StudentUpdateView, LecturerUpdateView, \
    TeachingRecordUpdateView, LevelView, DashboardDetailView, AttendanceDetailView, AttendanceAddView, \
    CourseAttendanceAddView, AttendanceUpdateView, decode_qr, add_student_to_course_attendance, FeedbackView, \
    CourseRegistrationView, CourseStudentsPDFView, AttendancePDFView, TeachingRecordPDFView, StudentPDFView, \
    DownloadTemplateFileView, LecturerPDFView, CourseListPDFView, DashboardUpdateView

# Create your urls here
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    # Class levels URLs
    path('levels/', LevelView.as_view(), name='levels'),

    # Course URLs
    path('app/<int:level_pk>/courses/', CourseView.as_view(), name='courses'),
    path('app/<int:level_pk>/courses/pdf/', CourseListPDFView.as_view(), name='courses_pdf'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>', CourseDetailView.as_view(), name='course_detail'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>/pdf/', CourseStudentsPDFView.as_view(), name='course_pdf'),
    path('app/<int:level_pk>/courses/add/', CourseAddView.as_view(), name='course_add'),
    path('app/<int:level_pk>/courses/<int:pk>/<slug:slug>/edit', CourseUpdateView.as_view(), name='course_update'),

    # Student URLs
    path('app/<int:level_pk>/students/', StudentView.as_view(), name='students'),
    path('app/<int:level_pk>/<str:model_name>/download-template/', DownloadTemplateFileView.as_view(), name='download_template'),
    path('app/<int:level_pk>/students/pdf/', StudentPDFView.as_view(), name='students_pdf'),
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/', StudentDetailView.as_view(), name='student_detail'),
    path('app/<int:level_pk>/students/add', StudentAddView.as_view(), name='student_add'),
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/edit/', StudentUpdateView.as_view(), name='student_update'),

    # Course Registration URLs
    path('app/<int:level_pk>/students/<int:pk>/<slug:slug>/register-courses/', CourseRegistrationView.as_view(),
         name='course_registration'),

    # Lecturer URLs
    path('app/<int:level_pk>/lecturers/', LecturerView.as_view(), name='lecturers'),
    path('app/<int:level_pk>/lecturers/pdf/', LecturerPDFView.as_view(), name='lecturers_pdf'),
    path('app/<int:level_pk>/lecturers/<int:pk>/<slug:slug>/', LecturerDetailView.as_view(),
         name='lecturer_detail'),
    path('app/<int:level_pk>/lecturers/add/', LecturerAddView.as_view(), name='lecturer_add'),
    path('app/<int:level_pk>/lecturers/<int:pk>/<slug:slug>/edit', LecturerUpdateView.as_view(),
         name='lecturer_update'),

    # Teaching Record URLs
    path('app/<int:level_pk>/records/', TeachingRecordView.as_view(), name='records'),
    path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/', TeachingRecordDetailView.as_view(),
         name='record_detail'),
path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/pdf/', TeachingRecordPDFView.as_view(),
         name='record_pdf'),
    path('app/<int:level_pk>/records/<int:pk>/<slug:slug>/edit', TeachingRecordUpdateView.as_view(),
         name='record_update'),

    # Dashboard URLs
    path('app/<int:level_pk>/<slug:level_slug>/', DashboardView.as_view(), name='dashboard'),
    path('app/<int:level_pk>/<slug:level_slug>/overview/', DashboardDetailView.as_view(), name='dashboard_detail'),
    path('app/<int:level_pk>/<slug:level_slug>/overview/update/', DashboardUpdateView.as_view(), name='dashboard_update'),

    # Attendance URLs
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/', AttendanceDetailView.as_view(),
         name='attendance_detail'),
path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/pdf/', AttendancePDFView.as_view(),
         name='attendance_pdf'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/edit/', AttendanceUpdateView.as_view(),
         name='attendance_update'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/add/', AttendanceAddView.as_view(), name='attendance_add'),

    # Enrollment URLs
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/admit/', CourseAttendanceAddView.as_view(),
         name='enroll_add'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/scan/', decode_qr, name='decode_qr'),
    path('app/<int:level_pk>/<slug:level_slug>/attendance/<int:pk>/scan/admit/', add_student_to_course_attendance,
         name='add_student_to_course_attendance'),

    # Feedback URLs
    path('app/feedback/', FeedbackView.as_view(), name='feedback'), 
]

templates/components/footer.html
{% load static %}
{% load tailwind_tags%}

<footer class="w-full p-8 bg-whiteColor {% if max_screen == 'xl' %} max-w-screen-xl {% else %} max-w-screen-lg {% endif %} m-auto my-5 px-4 py-6">
  <div class="separator flex gap-2 items-center justify-center {% if max_screen == 'xl' %} max-w-screen-xl {% else %} max-w-screen-lg {% endif %} m-auto mb-4">
    <hr class="w-full border-primaryColor border-dashed">
    <img src="{% static 'core/images/logo-shapes-primary.svg' %}" alt="" class="w-20">
    <hr class="w-full border-primaryColor border-dashed">
  </div>

  <div
    class="flex flex-row flex-wrap items-center justify-center text-center bg-whiteColor gap-y-2 gap-x-12 md:justify-between">
    <a href="{% url 'core:home' %}"><img src="{% static 'core/images/attendy-text.svg' %}" alt="Attendy" class="" /></a>
    <small class="block font-sans text-base antialiased font-normal leading-relaxed text-center text-blue-gray-900">
      © {{ current_year }} attendy. All rights reserved.
    </small>
    <div class="flex items-center gap-4 md:gap-2">
      <a href="https://linkedin.com/in/joelfah">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 24 24" width="24" height="24" fill="none">
          <path
            d="M4.5 9.5H4C3.05719 9.5 2.58579 9.5 2.29289 9.79289C2 10.0858 2 10.5572 2 11.5V20C2 20.9428 2 21.4142 2.29289 21.7071C2.58579 22 3.05719 22 4 22H4.5C5.44281 22 5.91421 22 6.20711 21.7071C6.5 21.4142 6.5 20.9428 6.5 20V11.5C6.5 10.5572 6.5 10.0858 6.20711 9.79289C5.91421 9.5 5.44281 9.5 4.5 9.5Z"
            stroke="currentColor" stroke-width="1.5" />
          <path
            d="M6.5 4.25C6.5 5.49264 5.49264 6.5 4.25 6.5C3.00736 6.5 2 5.49264 2 4.25C2 3.00736 3.00736 2 4.25 2C5.49264 2 6.5 3.00736 6.5 4.25Z"
            stroke="currentColor" stroke-width="1.5" />
          <path
            d="M12.326 9.5H11.5C10.5572 9.5 10.0858 9.5 9.79289 9.79289C9.5 10.0858 9.5 10.5572 9.5 11.5V20C9.5 20.9428 9.5 21.4142 9.79289 21.7071C10.0858 22 10.5572 22 11.5 22H12C12.9428 22 13.4142 22 13.7071 21.7071C14 21.4142 14 20.9428 14 20L14.0001 16.5001C14.0001 14.8433 14.5281 13.5001 16.0879 13.5001C16.8677 13.5001 17.5 14.1717 17.5 15.0001V19.5001C17.5 20.4429 17.5 20.9143 17.7929 21.2072C18.0857 21.5001 18.5572 21.5001 19.5 21.5001H19.9987C20.9413 21.5001 21.4126 21.5001 21.7055 21.2073C21.9984 20.9145 21.9985 20.4432 21.9987 19.5006L22.0001 14.0002C22.0001 11.515 19.6364 9.50024 17.2968 9.50024C15.9649 9.50024 14.7767 10.1531 14.0001 11.174C14 10.5439 14 10.2289 13.8632 9.995C13.7765 9.84686 13.6531 9.72353 13.505 9.63687C13.2711 9.5 12.9561 9.5 12.326 9.5Z"
            stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" />
        </svg>
      </a>

      <a href="https://x.com/FahDejon">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 24 24" width="24" height="24" fill="none">
          <path
            d="M3 21L10.5484 13.4516M21 3L13.4516 10.5484M13.4516 10.5484L8 3H3L10.5484 13.4516M13.4516 10.5484L21 21H16L10.5484 13.4516"
            stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
        </svg>
      </a>

      <a href="https://www.github.com/Joel-Fah"
        class="flex items-center gap-1.5 text-primaryColor px-2 py-0.5 rounded-full border border-primaryColor">
        <img src="{% static 'core/images/pfp.jpg' %}" alt="" class="w-5 rounded-full">
        Joël Fah
      </a>
    </div>
  </div>
</footer>

templates/components/message.html
{% if messages %}
<ul class="fixed w-auto max-w-80 bottom-4 right-4 z-50">
    {% for msg in messages %}
    <li>
        <div id="alert-{{ forloop.counter }}" class="flex items-center p-4 mb-4 backdrop-blur-xl rounded-2xl border
                {% if msg.tags == 'info' %} text-info border-info bg-info/10 
                    {% elif msg.tags == 'error' %} text-danger border-danger bg-danger/10
                        {% elif msg.tags == 'success' %} text-success border-success bg-success/10
                            {% else %} text-warning border-warning bg-warning/10
                {% endif %}" role="alert">

            {% if msg.tags == 'info' %}
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none"
                class="text-info">
                <path
                    d="M22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12Z"
                    stroke="currentColor" stroke-width="1.5" />
                <path
                    d="M12.2422 17V12C12.2422 11.5286 12.2422 11.2929 12.0957 11.1464C11.9493 11 11.7136 11 11.2422 11"
                    stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M11.992 8H12.001" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                    stroke-linejoin="round" />
            </svg>
            <span class="sr-only">Info</span>

            {% elif msg.tags == 'error' %}
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none"
                class="text-danger">
                <path d="M14.9994 15L9 9M9.00064 15L15 9" stroke="currentColor" stroke-width="1.5"
                    stroke-linecap="round" stroke-linejoin="round" />
                <path
                    d="M22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12Z"
                    stroke="currentColor" stroke-width="1.5" />
            </svg>
            <span class="sr-only">Error</span>

            {% elif msg.tags == 'success' %}
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none"
                class="text-success">
                <path
                    d="M22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22C17.5228 22 22 17.5228 22 12Z"
                    stroke="currentColor" stroke-width="1.5" />
                <path d="M8 12.5L10.5 15L16 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"
                    stroke-linejoin="round" />
            </svg>
            <span class="sr-only">Success</span>

            {% else %}
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="none"
                class="text-warning">
                <path
                    d="M5.32171 9.6829C7.73539 5.41196 8.94222 3.27648 10.5983 2.72678C11.5093 2.42437 12.4907 2.42437 13.4017 2.72678C15.0578 3.27648 16.2646 5.41196 18.6783 9.6829C21.092 13.9538 22.2988 16.0893 21.9368 17.8293C21.7376 18.7866 21.2469 19.6548 20.535 20.3097C19.241 21.5 16.8274 21.5 12 21.5C7.17265 21.5 4.75897 21.5 3.46496 20.3097C2.75308 19.6548 2.26239 18.7866 2.06322 17.8293C1.70119 16.0893 2.90803 13.9538 5.32171 9.6829Z"
                    stroke="currentColor" stroke-width="1.5" />
                <path
                    d="M12.2422 17V13C12.2422 12.5286 12.2422 12.2929 12.0957 12.1464C11.9493 12 11.7136 12 11.2422 12"
                    stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M11.992 8.99997H12.001" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                    stroke-linejoin="round" />
            </svg>
            <span class="sr-only">Warning</span>
            {% endif %}

            <div class="ms-3 text-sm font-medium select-none">
                {{ msg }}
            </div>
            <button type="button"
                class="ms-auto ml-2 -mx-1.5 -my-1.5 rounded-xl focus:ring-2 p-1.5 inline-flex items-center justify-center h-8 w-8 hover:bg-darkColor/10 transition-all duration-100 ease-linear"
                onclick="fadeOutAlert('alert-{{ forloop.counter }}')" 
                aria-label="Close">
                <span class="sr-only">Close</span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"
                    class="text-slate-400" fill="none">
                    <path d="M19.0005 4.99988L5.00049 18.9999M5.00049 4.99988L19.0005 18.9999" stroke="currentColor"
                        stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
            </button>
        </div>
    </li>

    <script>
        // Function to fade out the alert element
        function fadeOutAlert(alertId) {
            var alertElement = document.getElementById(alertId);
            var opacity = 1;
            var fadeOutInterval = setInterval(function () {
                if (opacity <= 0.1) {
                    clearInterval(fadeOutInterval);
                    alertElement.style.display = 'none';
                } else {
                    opacity -= 0.1;
                    alertElement.style.opacity = opacity;
                }
            }, 50);
        }

        // Automatically fade out after 10 seconds
        setTimeout(function () {
            fadeOutAlert('alert-{{ forloop.counter }}');
        }, 10000);
    </script>
    {% endfor %}
</ul>
{% endif %}

templates/components/meta.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Primary Meta Tags -->
<title>Attendy - Student Attendance Management System - {% block title %}{% endblock title %}</title>
<meta name="title" content="Attendy - Student Attendance Management System" />
<meta name="description" content="Welcome to Attendy, a web application designed to make student attendance management seamless and efficient. Whether you're a student, educator, or administrator, Attendy simplifies tracking attendance, organizing courses, and managing teaching records." />

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content="https://attendy-xsbr.onrender.com/" />
<meta property="og:title" content="Attendy - Student Attendance Management System" />
<meta property="og:description" content="Welcome to Attendy, a web application designed to make student attendance management seamless and efficient. Whether you're a student, educator, or administrator, Attendy simplifies tracking attendance, organizing courses, and managing teaching records." />
<meta property="og:image" content="https://github.com/Joel-Fah/images/blob/main/attendy_meta_image.png?raw=true" />

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content="https://attendy-xsbr.onrender.com/" />
<meta property="twitter:title" content="Attendy - Student Attendance Management System" />
<meta property="twitter:description" content="Welcome to Attendy, a web application designed to make student attendance management seamless and efficient. Whether you're a student, educator, or administrator, Attendy simplifies tracking attendance, organizing courses, and managing teaching records." />
<meta property="twitter:image" content="https://github.com/Joel-Fah/images/blob/main/attendy_meta_image.png?raw=true" />

<!-- Additional Meta Tags -->
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#ffffff">

<!-- Canonical Link -->
<link rel="canonical" href="https://attendy-xsbr.onrender.com/">

{# Favicon #}
<link rel="shortcut icon" href="{% static 'core/images/attendy.svg' %}" type="image/x-icon">